### ISSUE TITLE
Grant Permissions page based on Query string

### ISSUE THREAD

**Issue by kunjan13** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#12]
how can i give grant permission page based on query string of permission.
Because i have requirement that some customers might only allow read only and some might allow read&write permission.
So i would like to have a way to give consent page based on querystring of permissions.
As of now i don't see any way to do it. So do i have to create multiple AD application with different application permission?

**Comment by dstrockis** [comment]
Hey @kunjan13.  This is a feature that we've added in our 'v2' protocol: https://azure.microsoft.com/en-us/documentation/articles/active-directory-appmodel-v2-overview/, which is still in preview.  I think you'll find it meets your needs.

We're considering backporting it into the v1 protocol that this sample uses, but I'm not sure if it will provide the granularity you need.

**Comment by kunjan13** [comment]
So in v1, we get permissions only based on what we have selected in azure management portal for AD application?

**Comment by kalyankrishna1** [comment]
This feature is available using incremental consent in AAD v2.0. Try this sample https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/aspnetcore2-2-signInAndCallGraph
