### ISSUE TITLE
Issue with Multitenant

### ISSUE THREAD

**Issue by dilbaghrangi** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#13]
Hi ,

I have configured the applciation and Azure portal as per description but not able to login with different tenant user .
I can login only with the user of tenant whose client id is configured in application ..

**Comment by kalyankrishna1** [comment]
The sample has been heavily updated, including steps 
* register and consent the apps in multiple tenants
* to deploy this in the sovereign clouds. 
* to deploy this on Azure 
Please give the updated the sample a try and let us know on this thread if you have more issues.

**Comment by kalyankrishna1** [comment]
Closing as OP has not responded
