### ISSUE TITLE
How to recreate this sample.

### ISSUE THREAD

**Issue by OceanOSdev** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#16]
Would it be possible to add a "How to recreate this sample" section in the README.md like some of the other repos have?

**Comment by kalyankrishna1** [comment]
The sample is quiet old and targets AAD v1.0 and thus enhancements are limited. 
I'd suggest you generate a new VS.NET MVC project and use a folder diff tool to list the additions. Hint, there aren't a lot really..

**Comment by jmprieur** [comment]
Alternatively you could have a look at https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2, which explains the creation steps.
