### ISSUE TITLE
After setting application in Active directory, error during signup

### ISSUE THREAD

**Issue by shwetankhs** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#17]
After submitting application in Azure AD, error during signup

please check screen shot.
![error](https://cloud.githubusercontent.com/assets/19205978/15043049/12c80f52-127e-11e6-8cef-30b796eda70e.png)

**Comment by Eishpirate** [comment]
I'm having the same issue. Did you manage to resolve it?

**Comment by GiantZOC** [comment]
I found a fix for this issue here https://github.com/Azure-Samples/active-directory-dotnet-native-multitarget/issues/10

**Comment by kalyankrishna1** [comment]
We have provided some updated text in readme to ensure that you do not miss the admin consent steps. Please give them a try

**Comment by kalyankrishna1** [comment]
Closing as OP has not responded
