### ISSUE TITLE
Its only working for existing tenant, not for other tenant

### ISSUE THREAD

**Issue by shyambhiogade** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#18]
hi, 
i have created another tenant, but when i tried to sign in with that its not working.

In my Azure Active directory, i created new directory with new domain, do i need to assing any application to it. i get exception as

An exception of type 'System.IdentityModel.Tokens.SecurityTokenValidationException' occurred in TodoListWebApp.dll but was not handled in user code

what could be the reason

**Comment by johndonnelly** [comment]
Hello,

I got it to work all the way around. I had to change ProcessCode method to async in OnboardingController.cs

in particular:

AuthenticationResult result = await authContext.AcquireTokenByAuthorizationCodeAsync(
                    code, new Uri(Request.Url.GetLeftPart(UriPartial.Path)), credential);

**Comment by kalyankrishna1** [comment]
Good to know you made this work. One needs to pay attention to the resource they are obtaining tokens for. If its a different resource in a different tenant, token validation will fail.
