### ISSUE TITLE
Version using Oauth V2?

### ISSUE THREAD

**Issue by dmcweeney** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#19]
Hi,
Would it be possible to build a version of this sample that uses OAuth V2 - the new MSAL libraries and the App Registration done via the app registration portal?

This is what I am trying to do and it has my head so demented at this stage!

Thanks

Donal

**Comment by makerofthings7** [comment]
I don't think MSAL supports multi-tenant apps.... as of 12/9/16.

**Comment by dmcweeney** [comment]
I eventually got the onboarding part going with MSAL after much stress, but later discovered that MSAL registered apps could not use app certificate authentication against the likes of keyvault and azure sql server! So I went back to OAuth2 v1...

**Comment by kalyankrishna1** [comment]
Thr MSAL + AAD V2.0 samples are provided at https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code
