### ISSUE TITLE
Unhandled exception "System Error" if a user from the same tenant doesn't sign up

### ISSUE THREAD

**Issue by anujc** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#2]
Should a user from the same tenant need to sign up?
if the user simply signs in, unhandled exception is thrown

An exception of type 'System.IdentityModel.Tokens.SecurityTokenValidationException' occurred in TodoListWebApp.dll but was not handled in user code

Additional information: System error.

**Comment by kalyankrishna1** [comment]
Closing as no follow ups from the OP
