### ISSUE TITLE
"Working..." cannot sign-in (local sql db connection) 

### ISSUE THREAD

**Issue by twcarnahan** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#20]
From my visual version 2015, run app - 
I see the app and click "sign-in"
see my Azure registered App Name and proceed to sign-in
page switches to "Working..."
I have other examples working but can not get this Multi-Tenet one working - please help, Tim:
RESOLVED:
I had to use the below in web.config

  <connectionStrings>
    <add name="TodoListWebAppContext" connectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=C:\projects\TODOLISTWEBAPPCONTEXT.MDF;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False" providerName="System.Data.SqlClient" />
  </connectionStrings>

**Comment by DianeD** [comment]
Hi Tim. Did you click the **Sign Up** button before clicking **Sign In**, and go through the sign-up flow first? 

Usually the app worked as expected (either the app or the app's error page loaded), but one time I did reproduce the hang on the "Working" page when I clicked **Sign In** without first signing the user up. That time I got a SQL exception when accessing the db in the SecurityTokenValidated method in Startup.Auth.

**Comment by twcarnahan** [comment]
Diane,

Ok, I see the problem here -- I didn't know that we were creating a local SQL db. This time, I waited until I saw the error in the URL:

https://localhost:44302/Home/Error?message=A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 50 - Local Database Runtime error occurred. Cannot create an automatic instance. See the Windows Application event log for error details.%0d%0a)

---

I'll work on fixing this issue, nevertheless, getting to the issue at hand [😊]

Thank you for your patience, Tim:

________________________________

**Comment by twcarnahan** [comment]
Diane,


Is there a readme on the creation of this db as I've tried to recreate it manually although it should have created automatically --- what's the magic process here?


Always appreciate your help, Tim:

________________________________

**Comment by DianeD** [comment]
Hi TIm. I did not have to create a db or configure it.

Do you still get this error when you first click **Sign Up**? That's the only time I got the exception (though usually the exception was handled and I got the Error page).

![image](https://cloud.githubusercontent.com/assets/8431452/20979933/7f1a85ec-bc63-11e6-9f24-21adca0ce78d.png)

**Comment by twcarnahan** [comment]
Hello Diane,


Yes, I started over - and first thing was click "Sign Up"; this is when I get the error. It seems and you may want to check on your computer where you ran this, the code auto creates a db to store new registrations. It probable "auto created" on your machine.

Please advise as if so, I would like to reproduce the creation.

Tim:

________________________________

**Comment by DianeD** [comment]
Did you see this closed issue? It sounds like it's the same issue that you're seeing.

[https://github.com/Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect/issues/9](https://github.com/Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect/issues/9)

**Comment by twcarnahan** [comment]
Yes it's the same issue but the fix does not work for me.

There are other samples that "auto create" the db and work fine.


Ok well, back to the drawing board as this path is not working.

Tim:

________________________________

**Comment by DianeD** [comment]
Sorry it didn't work, Tim. There's also this question on StackOverflow that has several suggestions for resolving the error condition:

[http://stackoverflow.com/questions/26248293/sql-network-interfaces-error-50-local-database-runtime-error-occurred-canno](http://stackoverflow.com/questions/26248293/sql-network-interfaces-error-50-local-database-runtime-error-occurred-canno)

**Comment by twcarnahan** [comment]
Diane,


Thank you for your help, I might have the solution and will post.


Vr, Tim:

________________________________

**Comment by twcarnahan** [comment]
Diane,


When you got it to work, did you see the db that it created?

Vr, Tim:

________________________________

**Comment by DianeD** [comment]
Yes, it was automatically created in my (localdb)\v.11.0 instance.
________________________________

**Comment by twcarnahan** [comment]
This will resolved the local db problem I had with this project.
</configSections>
  <connectionStrings>
    <add name="TodoListWebAppContext" connectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=C:\projects\TODOLISTWEBAPPCONTEXT.MDF;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False" providerName="System.Data.SqlClient" />
  </connectionStrings>
  
  <appSettings>
