### ISSUE TITLE
Does not work on Azure as all Actve-Director-Dotnet-WebApps on Github What am I missing?!

### ISSUE THREAD

**Issue by Pelago** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#25]
Hi I have tested a lot of Sample Applications lately that uses Azure AD and/or Graph for User Authentication and user information. All Samples works perfectly on Development platform locally but as soon as you deploy to Azure Non of the samples are working.

This Sample for instance is lacing information of where the Task list Objects are stored. 
I assume it is in Local DB. For deployment on Azure do one need to add a connectionstring to a Azure SQL database?

Please advice on how to get this sample work on Azure. I have followed the instructions provided but..... something is missing

**Comment by kalyankrishna1** [comment]
The sample has been heavily updated, including steps 
* to deploy this in the sovereign clouds. 
* to deploy this on Azure 
Please give the updated the sample a try and let us know on this thread if you have more issues.

**Comment by kalyankrishna1** [comment]
Closing as OP has not responded
