### ISSUE TITLE
Multitenant application not working

### ISSUE THREAD

**Issue by parthabkp** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#27]
I have downloaded active-directory-dotnet-webapp-multitenant-openidconnect project, but can't sign up, getting error 
-----------------------------------------------------------

Additional technical information:
--
Correlation ID: 509e2036-18ee-4a86-90da-81cf14f20314
Timestamp: 2017-11-24 12:15:22Z
AADSTS50020: User account 'partha.bkp@gmail.com' from identity provider 'live.com' does not exist in tenant 'IMPActiveDir' and cannot access the application '2e6c9ae2-8733-41a6-9e01-ec1e14061c7e' in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

-----------------------------------------------------

**Comment by jmprieur** [comment]
@parthabkp, you need to sign-in with a work / school account, not an Microsoft personal account.
