### ISSUE TITLE
Model compatibility cannot be checked because the database does not contain model metadata

### ISSUE THREAD

**Issue by parthabkp** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#28]
I have created database on my local pc, 
I replace  base("TodoListWebAppContext") by base("Data Source=COM-59;Initial Catalog=ADMultiTenantDemo;User ID=sa;Password=manager;")
Now getting error Model compatibility cannot be checked because the database does not contain model metadata.

**Comment by kalyankrishna1** [comment]
The sample has been heavily updated, including steps to deploy this in the sovereign clouds. 
Please give the updated the sample a try and let us know on this thread if you have more issues.

**Comment by kalyankrishna1** [comment]
Closing as OP has not responded
