### ISSUE TITLE
Service to Service Multi Tenant App

### ISSUE THREAD

**Issue by joshidp** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#29]
Hi,

Thanks for sharing the knowledge.

I have a question. Can we have an app-to-app(no user) system with multi-tenancy?

E.g. ClientApp1 Calls ServerApp with one tenant and ClientApp2 calls with another tenant? So ServerApp and both the ClientApp's are all in different tenant directories.

Thanks

**Comment by kalyankrishna1** [comment]
Your scenario is more like a cross tenant service to service call and yes its possible. 
The service A in Tenant A, just needs the following to get an access token for Service B in tenant B
1. Use admin consent url to provision Service B in tenant A.
2. Set any required permissions between Service A and Service B.
2. Use the tenantID +  clientId + key (app key/certs) combination to obtain an access token to Service B
