### ISSUE TITLE
An administrator from the same tenant should not be asked for consent on sign up

### ISSUE THREAD

**Issue by anujc** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#3]
Since the administrator of the tenant has already provided permission "Enable sign-on and read users' profiles" on the Azure portal, he should not be asked fro consent when he tries to sign up

**Comment by kalyankrishna1** [comment]
Irrespective of whether an admin has consented or not, Azure Ad will ask for consent when a request with the following query parameter is sent to it. In your production apps, you'd use this option differently.

OnboardingController.cs
authorizationRequest += String.Format("&prompt={0}", Uri.EscapeDataString("admin_consent"));
