### ISSUE TITLE
Deployed to a non root directory in IIS and login fails since the redirection happens to /Onboarding/ProcessCode at the root directory

### ISSUE THREAD

**Issue by anujc** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#4]
Deployed to IIS to a non root folder like https://server/sites/sample and configured this as reply url. On trying to sign up, the login fails with the error
AADSTS70000: The redirect address &#39;https://server/Onboarding/ProcessCode&#39; is not valid.
The redirection should have happened to https://server/sites/sample/Onboarding/ProcessCode instead.

**Comment by kalyankrishna1** [comment]
The sample, for the sake of simplicity, assumes one level domain url, like https://server instead of https://server/sites/sample. Please scan the provided code and readme.md for code that works with URL and makes modifications accordingly
