### ISSUE TITLE
Database Table scripts

### ISSUE THREAD

**Issue by Nandhakumar2187** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#45]
Hi,
Is it possible to provide the database table scripts for this project?

**Comment by TiagoBrenck** [comment]
Hi @Nandhakumar2187, aren't your DB being created automatically?
If it isn't, one common reason is by not having a `App_Data` folder. Do create it, right click on **TodoListWebApp_MT** > **Add** > **New Folder** and name it as: **App_Data**. Leave this folder empty.

Did that solve your problem?

**Comment by TiagoBrenck** [comment]
Closing as we are archiving this sample. 

The newer one can be found at: https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-3-Multi-Tenant
