### ISSUE TITLE
China Azure Customization

### ISSUE THREAD

**Issue by rangeryu** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#5]
In case using China Azure 'Mooncake', we should replace all "_.windows.net"  with "_.chinacloudapi.cn" for the resource URLs including "login","sts" and "graph".

More reference: Developer Notes for Azure in China Applications http://msdn.microsoft.com/en-us/library/azure/dn578439.aspx

Test Passed.

**Comment by kalyankrishna1** [comment]
The sample has been heavily updated, including steps 
* register and consent the apps in multiple tenants
* to deploy this in the sovereign clouds. 
* to deploy this on Azure 
Please give the updated the sample a try and let us know on this thread if you have more issues.
