### ISSUE TITLE
Error provisioning for a single non-admin user

### ISSUE THREAD

**Issue by dgrala** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#8]
I was trying to sign up using a different tenant, regular user account. Instead of a consent dialog got this:

Sorry, but we’re having trouble signing you in. 
We received a bad request.

AADSTS70001: Application with identifier XXX was not found in the directory YYY.onmicrosoft.com

**Comment by dstrockis** [comment]
Hey Darek. Is the application XXX set as a multi-tenant application in the azure portal?

What was the domain of the user you attempted to sign in as? Was it YYY.onmicrosoft.com?

**Comment by darek-msft** [comment]
Yes and yes.

Provisioning with an admin account works.

Sent from my Windows Phone
________________________________

**Comment by dstrockis** [comment]
Does tenant YYY allow regular users to consent to applications?  There is a config switch to set this on the **Configure** tab of the tenant in the Azure portal.

If that switch is set correctly, please provide a correlationId and timestamp for the error and I can take a deeper look.

**Comment by darek-msft** [comment]
Thanks, I checked the settings and they should be able to consent.

Additional technical information:

Correlation ID: 98b9b314-b558-430d-a0e1-790459bad062

Timestamp: 2015-04-16 06:10:49Z

AADSTS70001: Application with identifier d0a17f8c-4463-47c2-ae03-04601528c5a3 was not found in the directory fbtest.onmicrosoft.com

**Comment by darek-msft** [comment]
Ping

**Comment by sanchezpablo** [comment]
I'm having the same problem using NEW azure portal, when I register a new native application with all the permissions needed and I try to obtain the access token using:

            AuthenticationResult authResult = null;
            string resource = "https://management.core.windows.net/";
            var authenticationContext = new AuthenticationContext("https://login.windows.net/" + tenantId);
            try
            {
                authResult = authenticationContext.AcquireToken(resource,
                    appId,
                    new UserCredential(
                        partnerCenterUser,
                        partnerCenterPassword
                    )
                );
            }
            catch (Exception ex)
            {
                throw;
            }
            return authResult;

I obtain the error message:

AADSTS70001: Application with identifier '4f7d5168-f754-42ed-a43d-1f0363ede30e' was not found in the directory tenantresellernew30.onmicrosoft.com
Trace ID: 182d19d7-68a7-4a48-bee1-f87486d31c66
Correlation ID: 75ef5bbb-06f9-4a06-a384-45860dae2568
Timestamp: 2016-10-13 07:32:25Z

I'm using sandbox account to perform the tests, but also in production we are facing this problem.

Any help is welcome because we are stucked and we need to integrate azure in our multi-tenant environment.

**Comment by karenpliu** [comment]
I have the same problem, does anyone have clue?

**Comment by grzewal** [comment]
Hi! 

I had this same problem and was able to resolve it. In the NEW portal you need to edit the manifest of the native application and set "availableToOtherTenants" flag to true. By default the NEW portal sets it to false (the old portal used to set it to true by default). 

HTH

**Comment by monubamb** [comment]
Thanks that helped resolve the problem

**Comment by dougahall** [comment]
Hi all,
I was able to run this sample successfully from a commercial AD tenant and login with users from multiple tenants. However, when I try to register the app in a government tenant, I'm having this same problem as the original poster.

- I have followed all the steps within the instructions.
- I've taken the specific steps outlined for making it work in Azure Government.
- Once completed, I can login with a user account in the government tenant that the app is registered but when attempting to login with a user from a different AD tenant I get the error (Application with identifier XXX was not found in the directory YYY).


Tenant Y allows users to consent to apps accessing company data on their behalf.
I have double-checked the app registration and the "availableToOtherTenants" flag is true.

Here is error including the correlation ID from my last attempt:

```
Correlation ID: f7b94d33-0aa9-4ea4-b2b2-13184d9d0f37
--
Timestamp: 2017-12-21 14:58:19Z
AADSTS70001: Application with identifier '9240c326-325a-48e2-8382-0efde95ee41e' was not found in the directory sasdomain1.onmicrosoft.com

```
Any help would be greatly appreciated.

**Comment by bforsyt4** [comment]
Thanks that worked for me.

**Comment by kalyankrishna1** [comment]
The sample has been heavily updated, including steps 
* register and consent the apps in multiple tenants
* to deploy this in the sovereign clouds. 
* to deploy this on Azure 
Please give the updated the sample a try and let us know on this thread if you have more issues.
